"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlayerDetailsService = exports.PortalsAuthenticationService = exports.UserManagementService = exports.UserCurrencyService = exports.LoginBonusService = exports.AuthenticationService = void 0;
const AuthenticationService_1 = require("./services/sdk/AuthenticationService");
Object.defineProperty(exports, "AuthenticationService", { enumerable: true, get: function () { return AuthenticationService_1.AuthenticationService; } });
const loginBonusService_1 = require("./services/sdk/loginBonusService");
Object.defineProperty(exports, "LoginBonusService", { enumerable: true, get: function () { return loginBonusService_1.LoginBonusService; } });
const userCurrencyService_1 = require("./services/sdk/userCurrencyService");
Object.defineProperty(exports, "UserCurrencyService", { enumerable: true, get: function () { return userCurrencyService_1.UserCurrencyService; } });
const userManagementService_1 = require("./services/sdk/userManagementService");
Object.defineProperty(exports, "UserManagementService", { enumerable: true, get: function () { return userManagementService_1.UserManagementService; } });
const portalsAuthenticationService_1 = require("./services/portals/portalsAuthenticationService");
Object.defineProperty(exports, "PortalsAuthenticationService", { enumerable: true, get: function () { return portalsAuthenticationService_1.PortalsAuthenticationService; } });
const playerDetailsService_1 = require("./services/portals/playerDetailsService");
Object.defineProperty(exports, "PlayerDetailsService", { enumerable: true, get: function () { return playerDetailsService_1.PlayerDetailsService; } });
